# Generated by Django 4.2 on 2025-10-29 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(help_text="List of user's skills")),
                ('interests', models.JSONField(help_text="List of user's interests")),
                ('education_level', models.CharField(help_text="User's education level", max_length=100)),
                ('work_style', models.CharField(help_text='Preferred work environment', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(help_text='Career title', max_length=200, unique=True)),
                ('description', models.TextField(help_text='What this career involves')),
                ('requirements', models.JSONField(help_text='Education, skills, certifications needed')),
                ('salary_info', models.JSONField(help_text='Entry, mid, senior level salary ranges')),
                ('job_growth', models.CharField(help_text='Job market growth outlook', max_length=100)),
                ('work_environment', models.TextField(blank=True, help_text='Typical work setting and conditions')),
                ('learning_resources', models.JSONField(blank=True, help_text='Courses, books, websites for learning', null=True)),
                ('related_careers', models.JSONField(blank=True, help_text='Similar or related career paths', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Detail',
                'verbose_name_plural': 'Career Details',
                'ordering': ['career_name'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(help_text='Name of the recommended career', max_length=200)),
                ('match_score', models.DecimalField(decimal_places=2, help_text='Match percentage (0-100)', max_digits=5)),
                ('confidence_level', models.CharField(choices=[('Very High', 'Very High'), ('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low')], help_text='Confidence level of recommendation', max_length=20)),
                ('rank', models.IntegerField(help_text='Rank in top 5 (1-5)')),
                ('matching_skills', models.JSONField(help_text='Skills user has that match this career')),
                ('missing_skills', models.JSONField(help_text='Skills user needs to learn for this career')),
                ('completeness_percent', models.DecimalField(decimal_places=2, help_text='Skill completeness percentage', max_digits=5)),
                ('rationale', models.JSONField(blank=True, help_text='Detailed explanation of recommendation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.assessment')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['assessment', 'rank'],
            },
        ),
    ]
